target/riscv: Implement ability to re-examine target
riscv/riscv-openocd pull request #1020
Opened 2024-02-21 15:48 UTC by kr-sc

Add a new OpenOCD command `re_examine` to enforce re-examination of target. Some of existing hardware have a writable misa.V bit. It means that it can be enabled by software. We need an opportunity to enforce `examine` procedure in OpenOCD to query the capabilities of the target.

Also this patch includes commit with fix of a little issue connected with clearing triggers cacge.

2024-02-22 13:01 UTC, MarekVCodasip requested changes
Thanks for the patch. I have found a few things.

I would like others to also take a look, I have a feeling that re-examination needs more discussion.

2024-02-22 13:01 UTC, MarekVCodasip commented on doc/openocd.texi
> +@subsection RISC-V Syntacore hardware-specific Commands
I would not call this a Syntacore hardware-specific command.

Spike also has the ability to change at runtime which extensions are implemented. The RISC-V specification does allow the ISA to change at runtime if the hardware supports it.

2024-02-22 13:01 UTC, MarekVCodasip commented on src/target/target.h
> +
I am not sure if touching target.h/c is the best approach.

Myself, I would open a patch on the upsteam OpenOCD changing the visibility of this function.

For now, I would set the `target->examined = false` directly in the handle_re_examine_target() and add a // TODO to change it later.

2024-02-22 13:01 UTC, MarekVCodasip commented on src/target/riscv/riscv.c
> +		LOG_TARGET_ERROR(target, "Please, remove all breakpoints and watchpoints.");
I would change the message, something akin to: "Re-examination requires the removal of all breakpoints and watchpoints."

2024-03-15 07:17 UTC, aap-sc commented on doc/openocd.texi
> +@subsection RISC-V Syntacore hardware-specific Commands
> I would not call this a Syntacore hardware-specific command.

This is a mistake on our part. This code was a while in Syntacore codebase and we missed this part during internal review.

2024-03-15 07:22 UTC, aap-sc commented
NOTE: @MarekVCodasip Kirill will be out for a while... This patch won't get any updates because of this for some time. Likely, we'll refactor the a little bit and re-upload it again. In any case - thanks for review, the suggested changes will be integrated.

2024-05-28 10:41 UTC, closed without merging