Don't use MMU in M mode - https://github.com/riscv/riscv-openocd/issu…
riscv/riscv-openocd pull request #479
Opened 2020-05-20 14:47 UTC by TM1234

Fix for https://github.com/riscv/riscv-openocd/issues/474

2020-05-20 20:02 UTC, timsifive requested changes
Thanks for addressing this, Tommy.

What testing did you do?

2020-05-20 20:02 UTC, timsifive commented on src/target/riscv/riscv.c
> +	    (riscv_get_register(target, &mstatus, GDB_REGNO_MSTATUS) == ERROR_OK) &&
priv (part of DCSR) and mstatus are both required to be implemented, so if we can't read them I think we should return error here.

2020-05-20 20:02 UTC, timsifive commented on src/target/riscv/riscv.c
> +		LOG_DEBUG("SATP/MMU ignored in M mode.");
Can you add the value of mstatus to this error message? That way I'll at least have something to go on when somebody reports they got this error message for no good reason.

2020-05-20 20:16 UTC, timsifive commented
As to your performance impact questions. There are two more register reads, but both dcsr and mstatus reads should be cached. You should be able to confirm this easily by looking at the debug log, because riscv_mmu() is called every time OpenOCD starts any memory access.

2020-05-20 20:54 UTC, TM1234 commented
Thanks for the comments and feedback @timsifive.
I will address the issues that you mention above and resubmit it.
I have only tested in M mode so not when the target is in any lower privilege mode - explicitly or via mstatus.mprv/mpp.

2020-05-22 20:25 UTC, timsifive approved these changes
Thanks, Tommy! I'll merge this next week.

2020-05-22 21:22 UTC, timsifive commented
I just confirmed that all riscv-tests/debug still pass.

2020-05-22 21:32 UTC, TM1234 commented
Thanks a lot @timsifive.

2020-05-26 17:33 UTC, merged