Allocate RISC-V arch_info during target creation
riscv/riscv-openocd pull request #531
Opened 2020-09-14 07:43 UTC by JanMatCodasip

* Ensured that target->arch_info is allocated as soon as the
  target is created. Needed so that per-target config commands
  (e.g. "riscv set_mem_access") can be executed also in the
  OpenOCD's config phase (before calling "init").

* Added several assert()'s for safety.

Signed-off-by: Jan Matyas <matyas@codasip.com>

2020-09-14 08:23 UTC, JanMatCodasip commented
This change brings the ability to call per-target RISC-V configuration commands also in the OpenOCD's configuration phase (for example `riscv set_mem_access`). At the same time, it is a ground-work for https://github.com/riscv/riscv-openocd/issues/527.

This change supersedes #530. If this change is all right, please close #530.

This has been tested manually and also via `riscv-tests/debug`, all passed.

2020-09-15 18:09 UTC, timsifive requested changes
Thanks for jumping on this. Can you take out that comment and move the discussion elsewhere?

2020-09-16 06:41 UTC, JanMatCodasip commented
Sure, I have removed the TODO comment and instead noted the idea under https://github.com/riscv/riscv-openocd/issues/534 so that it won't get lost.

2020-09-16 20:51 UTC, timsifive approved these changes
Looks good. I'll merge this tomorrow.

2020-09-17 20:20 UTC, merged