riscv: workaround to disable hwbp triggers during a "step" operation
riscv/riscv-openocd pull request #741
Opened 2022-10-05 10:11 UTC by aap-sc

When step operation is requested debug triggers are expected to be disabled. However, the current implementation only takes triggers corresponding to OpenOCD-managed watchpoints into account (unless manual_hwbp_set flag is set).

This commit implements a simple workaround by piggy-backing on manual_hwbp_set branch to take hardware breakpoints into account too. This fixes a situation when step operation does work because of a hwbp match.

A more efficient implementation would uniformly iterate over OpenOCD-managed hardware breakpoints and watchpoints to detect triggers to disable - but it looks like this may require some refactoring, while this commit just focuses on fixing the "step" operation.

2022-10-05 16:09 UTC, timsifive commented
How does this problem show up? gdb already clears/sets hardware breakpoints for a step.

2022-10-05 16:10 UTC, aap-sc commented
> How does this problem show up? gdb already clears/sets hardware breakpoints for a step.

For example - if you connect to openocd via telnet and try to do some debug without gdb.

2022-10-05 16:14 UTC, timsifive commented
That seems like it should be solved at the general target level, not inside the RISC-V-specific code. E.g. in target_step() of target.c. I'd e-mail the OpenOCD mailing list about this problem. It's possible that there already is a general solution to this problem, for instance using callbacks.

2022-10-05 16:16 UTC, aap-sc commented
> That seems like it should be solved at the general target level, not inside the RISC-V-specific code. E.g. in target_step() of target.c. I'd e-mail the OpenOCD mailing list about this problem. It's possible that there already is a general solution to this problem, for instance using callbacks.

Oh. I was not aware of that. For whatever reason I thought that it was only riscv-specific problem.  Will take a look at the mailing list then.

2022-10-10 21:28 UTC, aap-sc commented
@timsifive , regarding this one:

> That seems like it should be solved at the general target level, not inside the RISC-V-specific code. E.g. in target_step() of target.c. I'd e-mail the OpenOCD mailing list about this problem. It's possible that there already is a general solution to this problem, for instance using callbacks.

I've looked at how existing targets handle similar problem. Turns out:
1. The issue with riscv target is not limited to only hwbp. Any breakpoints is affected.
2. You were right - the original proposal was completely incorrect.
3. There is this **handle_breakpoints** parameter passed to the target-specific handler. It controls if  target-specific handler should disable the existing breakpoints. gdbserver sets it to "0", while TCL server sets is to "1".

I've edited the original description and updated PR. Could you please take a look once again?

2022-10-12 16:33 UTC, timsifive requested changes
This looks good overall. Did you run the tests in [riscv-tests/debug](https://github.com/riscv-software-src/riscv-tests/tree/master/debug)?

2022-10-12 16:33 UTC, timsifive commented on src/target/riscv/riscv.c
> +	LOG_DEBUG("stepping hart");
```suggestion
	LOG_TARGET_DEBUG(target, "stepping hart");
```

2022-10-12 16:33 UTC, timsifive commented on src/target/riscv/riscv.c
> +		LOG_ERROR("unable to restore the disabled breakpoint");
```suggestion
		LOG_TARGET_ERROR(target, "unable to restore the disabled breakpoint");
```

2022-10-13 10:56 UTC, aap-sc commented
> Did you run the tests in [riscv-tests/debug](https://github.com/riscv-software-src/riscv-tests/tree/master/debug)?

yep. I've run `make all-tests` from the riscv-tests/debug directory. It looks like everything pass.

2022-10-13 17:12 UTC, timsifive approved these changes
Thank you!

2022-10-14 16:40 UTC, merged