Cjtag
riscv/riscv-openocd pull request #744
Opened 2022-10-07 13:41 UTC by mrv96

2022-10-07 15:55 UTC, timsifive requested changes
This change removes `case CJTAG_RESET` altogether when BUILD_FTDI_CJTAG isn't 1. I bet that leads to a compiler warning or even error. Can you leave the original structure in place, so `case CJTAG_RESET` is defined but doesn't do anything when BUILD_FTDI_CJTAG isn't 1?

2022-10-07 18:31 UTC, mrv96 commented
@timsifive the removed case is `case JTAG_RESET` not `case CJTAG_RESET`. It doesn't produce neither warnings nor errors, otherwire CI/CD pipeline of this PR would fails in building steps.

I took the decision to remove `case JTAG_RESET` because it has been removed from the upstream. You can check it here: https://github.com/openocd-org/openocd/blob/ae937791d35b0820e0bc9bf0ab134c2bebd113e4/src/jtag/drivers/ftdi.c#L597-L625

Are you sure that I should leave the original case structure?

2022-10-07 18:49 UTC, timsifive commented
I would have expected you to get an error because not every value in the enum is accounted for. But testing it, that is not the case. I guess the default clause saves you. So this is OK.

2022-10-07 18:55 UTC, timsifive approved these changes
Looks good to me. @SiFiveGregS can you confirm this looks fine?

2022-10-08 00:27 UTC, SiFiveGregS approved these changes
This change looks right, in the sense that the old code would have apparently tried to move the JTAG state before any post-reset cJTAG setup was done, which looks like it was wrong.  I guess that particular situation wasn't universally seen; evidently it's been lurking.

2022-10-10 16:43 UTC, merged