target/riscv: Correctly set target->state in deassert_reset
riscv/riscv-openocd pull request #750
Opened 2022-10-19 16:39 UTC by timsifive

This bug didn't lead to problems that I can see, but it would with some upcoming changes. It might fix #749.

Change-Id: I552acbae9977150c4c9e573f8852033bc80fcebb
Signed-off-by: Tim Newsome <tim@sifive.com>

2022-10-20 13:17 UTC, JanMatCodasip approved these changes

2022-10-20 13:26 UTC, JanMatCodasip requested changes

2022-10-20 13:26 UTC, JanMatCodasip commented on src/target/riscv/riscv-013.c
>  		target->debug_reason = DBG_REASON_DBGRQ;
I don't think any code should look at `target->debug_reason` when `target->state == TARGET_RUNNING`. But for clarity & robustness, we better keep those two aligned:

```suggestion
		if (target->reset_halt) {
			target->state = TARGET_HALTED;
			target->debug_reason = DBG_REASON_DBGRQ;
		} else {
			target->state = TARGET_RUNNING;
			target->debug_reason = DBG_REASON_NOTHALTED;
		}
```

2022-10-20 17:25 UTC, SiFiveGregS approved these changes

2022-10-21 06:35 UTC, JanMatCodasip approved these changes

2022-10-21 16:16 UTC, merged