Calculate the FreeRTOS type sizes and offsets more adaptively.
riscv/riscv-openocd pull request #806
Opened 2023-03-01 08:41 UTC by Du-Chao

The definition of TickType_t varies between different targets. And it is also related to configUSE_16_BIT_TICKS option. Thus introduce a new command to make sure we are using a correct ticktype size.

2023-03-02 17:39 UTC, timsifive requested changes
I like adding the command.

2023-03-02 17:39 UTC, timsifive commented on src/rtos/FreeRTOS.c
> +static const struct command_registration freetros_commands[] = {
```suggestion
static const struct command_registration freertos_commands[] = {
```

2023-03-02 17:39 UTC, timsifive commented on src/rtos/FreeRTOS.c
> +		"calculation of offsets and sizes is correct. Defaults to 4."
Please document this command in `doc/openocd.texi` as well.

2023-03-02 17:39 UTC, timsifive commented on src/rtos/FreeRTOS.c
> +static unsigned freertos_ticktype_size = 4;
```suggestion
static unsigned int freertos_ticktype_size = 4;
```
OpenOCD style requires this. I realize that this file uses plain `unsigned` all over the place. Some day I'll have to fix that, but for now I'm trying to at least have new code conform to the new style.

2023-03-02 17:39 UTC, timsifive commented on src/rtos/FreeRTOS.c
> +	unsigned size;
```suggestion
	unsigned int size;
```

2023-03-03 08:43 UTC, Du-Chao commented
Thanks Tim for the review and comment.

I will commit a new patch later. (for the doc part, I need to check where is the right place to insert this new command.)

2023-03-06 23:24 UTC, timsifive approved these changes

2023-03-09 00:24 UTC, merged