target/riscv: fix register access on running target
riscv/riscv-openocd pull request #854
Opened 2023-05-29 16:24 UTC by en-sc

Register access on running target should fail if mstatus needs to be modified.

Change-Id: Iec8e8d514ef2f5ca42606a5534cce55aaaa99180

2023-05-29 16:29 UTC, en-sc commented
For a detailed description of the issue, please refer to this [discussion](https://github.com/riscv/riscv-openocd/pull/842#discussion_r1178500114).

2023-05-31 16:07 UTC, timsifive requested changes
This looks good to me. Abstract register accesses are still attempted when running, but we won't try to modify mstatus while running, which would lead to confusing behavior.

2023-05-31 16:07 UTC, timsifive commented on src/target/riscv/riscv-013.c
> +			"The target should be halted to modify and then restore mstatus");
```suggestion
			"The target must be halted to modify and then restore mstatus");
```

2023-05-31 19:26 UTC, en-sc commented on src/target/riscv/riscv-013.c
> +			"The target should be halted to modify and then restore mstatus");
Addressed.

2023-06-01 00:00 UTC, timsifive approved these changes

2023-06-02 15:25 UTC, merged