target/riscv: prevent the fence.i from triggering the exception
riscv/riscv-openocd pull request #898
Opened 2023-08-01 16:46 UTC by wxjstz

On platforms that do not support Zifencei, executing fence.i will trigger an exception, this patch eliminates the impact of the exception

Change-Id: I459cff096374064fdb6e18a9d95170510ae1f32e

2023-08-01 18:17 UTC, wxjstz commented
please review it @timsifive @TommyMurphyTM1234

2023-08-01 18:20 UTC, wxjstz commented
The patch requires progbufsize > 1, is this a issue?

2023-08-07 13:28 UTC, MarekVCodasip requested changes
Thanks for the patch. This can actually work when `progbufsize == 1` on some targets, but not for a good reason.

I think if you remove the code surrounding the `mtvec`, it will work fine. It does make me wonder what is the purpose of it in the first place.

2023-08-07 13:28 UTC, MarekVCodasip commented on src/target/riscv/riscv-013.c
> +		return result;
This isn't great.
This basically loads an address as an instruction into the program buffer (if it is even memory mapped). It is then rewritten when the fence_i is written into the program buffer and executed.

2023-08-08 01:51 UTC, wxjstz commented
> The exceptions don't trigger in program buffer

why?  Can you tell me which spce this information comes from？

2023-08-08 05:36 UTC, MarekVCodasip commented
> why? Can you tell me which spce this information comes from？

Alright. It is a bit more general. They don't trigger in debug mode in general.

https://github.com/riscv/riscv-debug-spec/blob/master/riscv-debug-stable.pdf its currently on page 50 in section 4.1

2023-08-08 06:21 UTC, wxjstz commented
> > why? Can you tell me which spce this information comes from？
> 
> Alright. It is a bit more general. They don't trigger in debug mode in general.
> 
> https://github.com/riscv/riscv-debug-spec/blob/master/riscv-debug-stable.pdf its currently on page 50 in section 4.1

Thank you!

2023-08-08 06:21 UTC, closed without merging

2023-08-08 06:51 UTC, MarekVCodasip commented
Don't close this, separating the two fences into two separate program buffer executions is still good and useful.