target/riscv: fix execute_fence
riscv/riscv-openocd pull request #903
Opened 2023-08-08 06:43 UTC by wxjstz

This patch improves the following issues:
1. Makes it compatible with targets with progbufsize == 1.
2. Although exceptions don’t update any registers, but  do end execution of the progbuf. This will make fence rw, rw impossible to execute.

Change-Id: I2208fd31ec6a7dae6e61c5952f90901568caada6

2023-08-08 06:44 UTC, wxjstz commented
@MarekVCodasip

2023-08-08 06:49 UTC, wxjstz commented
[riscv-debug-stable.pdf](https://github.com/riscv/riscv-debug-spec/blob/master/riscv-debug-stable.pdf) page 50 section 4.1
>3. Exceptions don’t update any registers. That includes cause, epc, tval, dpc, and mstatus. They do end execution of the Program Buffer.

2023-08-08 08:59 UTC, MarekVCodasip approved these changes, later dismissed
Visually, it looks fine.

2023-08-14 06:29 UTC, MarekVCodasip commented
Good catch.

2023-08-14 06:29 UTC, MarekVCodasip submitted a review, later dismissed

2023-08-14 20:08 UTC, timsifive requested changes
I think it's worth making two code paths: one which executes both instructions at once (old way), and another which executes them individually (new way).

The reason is that execute_fence() is called from read_memory_progbuf() and write_memory_progbuf(), which can be called quite a lot when a debugger is accessing complex structs from memory.

2023-08-15 05:35 UTC, JanMatCodasip commented
> I think it's worth making two code paths: one which executes both instructions at once (old way), and another which executes them individually (new way).

In that case, the algorithm could be:

```
if (progbufsize >= 2 && fence_i_supported):
    execute_fence_and_fence_i()
else:
    execute_fence()
    if fence_i_supported():
        execute_fence_i()
```

@timsifive Is it what you have in mind?

2023-08-17 01:06 UTC, wxjstz commented
> I think it's worth making two code paths: one which executes both instructions at once (old way), and another which executes them individually (new way).
> 
> The reason is that execute_fence() is called from read_memory_progbuf() and write_memory_progbuf(), which can be called quite a lot when a debugger is accessing complex structs from memory.

done

2023-08-17 16:30 UTC, timsifive approved these changes

2023-08-18 16:32 UTC, merged

2023-08-18 16:45 UTC, EccoTheDolphin commented on src/target/riscv/riscv-013.c
> +	int result;
it looks like we don't really need this `result` variable here. @wxjstz maybe we could cleanup this?