Be more clear in multi-core systems without -rtos
riscv/riscv-openocd pull request #91
Opened 2017-08-11 21:11 UTC by timsifive

Don't print out there's a hart with XLEN of 0.

2017-08-11 21:20 UTC, palmer-dabbelt requested changes
This looks good, but before we merge it I'd like to make sure riscv-tests is correctly running the tests and fix the regression from https://github.com/riscv/riscv-openocd/pull/90 .

2017-08-11 21:22 UTC, timsifive commented
Sure. I just wanted this to not get lost in my mess of local branches.

2017-08-11 21:23 UTC, palmer-dabbelt commented
Ya, no problem.

2017-09-18 18:55 UTC, timsifive commented
#90 merged a while ago. I just ran the sim tests against this code again, and it works fine. Can you approve the change?

2017-09-19 19:33 UTC, palmer-dabbelt approved these changes
Sorry about that, I just missed this going by again.

2017-09-19 19:53 UTC, merged