target/riscv_semihosting: Make the unknown operation number an error
riscv/riscv-openocd pull request #912
Opened 2023-09-06 11:06 UTC by MarekVCodasip

Previously, an unknown semihosting operation number was logged as debug. This patch changes it and few other places to be logged as error instead.

Change-Id: I83cae5ca1e3daed440f92b08bd372bfffbbad63c

2023-09-06 12:30 UTC, JanMatCodasip requested changes
This looks OK. Please just make the error messages more clear to the user.

2023-09-06 12:30 UTC, JanMatCodasip commented on src/target/riscv/riscv_semihosting.c
> +			LOG_TARGET_ERROR(target, "   -> ERROR (couldn't read a0)");
Now that these messages become more user-visible, please consider printing a full sentence. For example:

```suggestion
			LOG_TARGET_ERROR(target, "Could not read semihosting operation code (register a0)");
```

2023-09-06 12:30 UTC, JanMatCodasip commented on src/target/riscv/riscv_semihosting.c
> +			LOG_TARGET_ERROR(target, "   -> ERROR (couldn't read a1)");
```suggestion
			LOG_TARGET_ERROR(target, "Could not read semihosting address (register a1)");
```

2023-09-06 12:30 UTC, JanMatCodasip commented on src/target/riscv/riscv_semihosting.c
> +			LOG_TARGET_ERROR(target, "   -> NONE (unknown operation number)");
```suggestion
			LOG_TARGET_ERROR(target, "Unknown semihosting operation requested (op = 0x%x)", semihosting->op);
```

2023-09-06 12:40 UTC, JanMatCodasip commented
The main reason for the change is to notify the user in case an unknown semihosting operation is requested -- that is the third error message. 

The previous two errors (unable to read a0 or a1) should be very unlikely to happen.

2023-09-06 12:58 UTC, TommyMurphyTM1234 commented
> The main reason for the change is to notify the user in case an unknown semihosting operation is requested -- that is the third error message.
> 
> The previous two errors (unable to read a0 or a1) should be very unlikely to happen.

Surely the failure to read `a0` or `a1` should have an error message that reflects that situation rather than implying that it's an "unknown" semihosting request?

2023-09-06 14:22 UTC, JanMatCodasip commented
> Surely the failure to read `a0` or `a1` should have an error message [...]

And yes, those error messages are part of this change, too.

2023-09-07 06:08 UTC, MarekVCodasip commented on src/target/riscv/riscv_semihosting.c
> +			LOG_TARGET_ERROR(target, "   -> ERROR (couldn't read a0)");
Done

2023-09-07 06:08 UTC, MarekVCodasip commented on src/target/riscv/riscv_semihosting.c
> +			LOG_TARGET_ERROR(target, "   -> ERROR (couldn't read a1)");
Done

2023-09-07 06:08 UTC, MarekVCodasip commented on src/target/riscv/riscv_semihosting.c
> +			LOG_TARGET_ERROR(target, "   -> NONE (unknown operation number)");
Done

2023-09-07 10:00 UTC, JanMatCodasip approved these changes

2023-09-07 17:03 UTC, timsifive approved these changes

2023-09-08 16:22 UTC, merged