target/riscv: Stop caching writes to DPC
riscv/riscv-openocd pull request #952
Opened 2023-11-03 11:09 UTC by MarekVCodasip

Since DPC is WARL (same rules as MEPC according to the specification), it is possible that
writes to it won't result in the exact value present. Therefore, writes to it shouldn't be cached, same as with other MEPC registers.

Change-Id: Ib7a4041bc2730c3cd40d5a4db8ba52a8e8788256

2023-11-03 11:36 UTC, JanMatCodasip approved these changes
We have already discussed and reviewed it with Marek internally.

2023-11-03 21:21 UTC, timsifive requested changes
But we can still cache it for reads, right? So for DPC it should really return !is_write.

2023-11-06 05:52 UTC, JanMatCodasip commented
I believe that's right. And that's exactly what the code says on line 4980. https://github.com/riscv/riscv-openocd/pull/952/files#diff-b4aa16f9e42cb8f0934baa7c8e0ec9c70a369bef98b99b26ae2e896c8aa95d6aR4980

It is just not immediately apparent due to the diff shown being too short :-)

2023-11-06 17:12 UTC, timsifive approved these changes
Thanks for explaining, @JanMatCodasip.

2023-11-07 17:04 UTC, merged