Update riscv/debug_defines (to sync with riscv-debug-spec commit 40b9a05)
riscv/riscv-openocd pull request #973
Opened 2023-12-04 09:06 UTC by kr-sc

Change-Id: Ie969866d1de83360a5f45e96e22108b58b8aa02f

2023-12-05 20:19 UTC, timsifive submitted a review, later dismissed
Looks OK. Just to check, can you show some debug output that uses the new code?

2023-12-06 09:04 UTC, en-sc commented
I would suggest updating to a more recent version to include these changes: https://github.com/riscv/riscv-debug-spec/pull/908, https://github.com/riscv/riscv-debug-spec/pull/909. Please, note that `debug_reg_printer.[ch]` should also be updated if the changes are included.

2023-12-06 14:10 UTC, kr-sc commented
> Looks OK. Just to check, can you show some debug output that uses the new code?

Before:
```
log_debug_reg(): [riscv.cpu] dtmcs=0x61 { version=1.0, dmistat=0, idle=0, dmireset=0, dtmhardreset=0, errinfo=not implemented, abits=6, }
```

After:
```
log_debug_reg(): [riscv.cpu] dtmcs=0x61 {version=1_0 errinfo=not_implemented abits=6}
```

2023-12-07 00:13 UTC, timsifive commented
I made https://github.com/riscv/riscv-debug-spec/pull/922 to address the checkpatch issue. When that merges, please update this PR.

2023-12-08 22:34 UTC, timsifive approved these changes

2023-12-11 07:13 UTC, JanMatCodasip requested changes
I have few suggestions related to code structure or naming. Otherwise this looks good.

2023-12-11 07:13 UTC, JanMatCodasip commented on src/target/riscv/debug_reg_printer.h
> +enum riscv_debug_reg_show {
Please, could you give a descriptive name to this enum, e.g. `display_mode` (or similar), rather than `show`.

```suggestion
enum riscv_debug_reg_display_mode {
```

2023-12-11 07:13 UTC, JanMatCodasip commented on src/target/riscv/debug_reg_printer.c
> +	enum riscv_debug_reg_show show)
```suggestion
	enum riscv_debug_reg_display_mode display_mode)
```

2023-12-11 07:13 UTC, JanMatCodasip commented on src/target/riscv/debug_reg_printer.c
> +		}
The condition of the "if" is complex, which makes it hard to understand and modify. Please, could you simplify this whole part of the code - for example as shown below.

```suggestion

		uint64_t field_value = riscv_debug_reg_field_value(list.field, value);

		const bool isZero = (field_value == 0);
		const bool isUnnamed = (!list.field.values) || (!list.field.values[0]);		
		
		if (display_mode == RISCV_DEBUG_REG_HIDE_UNNAMED_0 && isUnnamed && isZero)
			// Don't display this field
			continue;
			
		if (display_mode == RISCV_DEBUG_REG_HIDE_ALL_0 && isZero)
			// Don't display this field
			continue;			
		
		// Show this field
		curr += get_len_or_sprintf(buf, curr, separator);
		curr += riscv_debug_reg_field_to_s(buf, curr, list.field, context,
							field_value);
		separator = " ";		
		
```

2023-12-11 10:54 UTC, kr-sc commented
@JanMatCodasip I think that we need patch to debus spec with your suggestions. What if we merge this patch and make a subsequent update with your suggestions to debug spec and openocd later?

2023-12-11 13:13 UTC, JanMatCodasip commented
> kr-sc: I think that we need patch to debug spec with your suggestions.

Ah, when looking at the changes, I missed the fact that the files `debug_reg_printer.*` are auto-generated from the debug spec repository. Thank you for the reminder.

> What if we merge this patch and make a subsequent update with your suggestions to debug spec and openocd later?

Sure, I agree, let's merge this now as is.

If you are happy with the suggested changes, I believe it would be good to apply them to the riscv-debug-spec repo.

2023-12-11 13:14 UTC, JanMatCodasip approved these changes

2023-12-11 13:15 UTC, JanMatCodasip commented on src/target/riscv/debug_reg_printer.h
> +enum riscv_debug_reg_show {
Correction per [kr-sc's comment](https://github.com/riscv/riscv-openocd/pull/973#issuecomment-1849825669): This change should go to the debug spec repository instead (riscv-debug-spec).

2023-12-11 13:15 UTC, JanMatCodasip commented on src/target/riscv/debug_reg_printer.c
> +	enum riscv_debug_reg_show show)
Same as above: This change should go to the debug spec repository instead (riscv-debug-spec).

2023-12-11 13:16 UTC, JanMatCodasip commented on src/target/riscv/debug_reg_printer.c
> +		}
Same as above: This change should go to the debug spec repository instead (riscv-debug-spec).

2023-12-11 17:05 UTC, merged