target/riscv: move read redirection for `priv` to `riscv-013.c`
riscv/riscv-openocd pull request #997
Opened 2024-01-17 14:54 UTC by en-sc

The reason for the change is a conflict: `dcsr[5]` is `dcsr.v` in current spec, but it is `dcsr.debugint` in 0.11. This causes `priv` register to be read incorrectly.

Change-Id: If2d8fdcd8536afa4c7149c453101b00ce0df1ce0

2024-01-17 15:07 UTC, en-sc commented
@lz-bro, FYI.

2024-01-17 15:25 UTC, TommyMurphyTM1234 commented
Confirmed as working with SiFive HiFive1 Rev A01:

* https://github.com/riscv/riscv-openocd/issues/996#issuecomment-1896039265

2024-01-18 08:15 UTC, JanMatCodasip commented
FYI, I will probably be able to review this on Monday.

2024-01-23 14:42 UTC, MarekVCodasip requested changes
Otherwise, it looks fine to me.

2024-01-23 14:42 UTC, MarekVCodasip commented on src/target/riscv/riscv-013.c
> +	/* This would be nice to move this redirection, to version-independent part,
I would reword this:
```suggestion
	/* It would be beneficial to move this redirection to the version-independent section,
```

2024-01-23 14:52 UTC, en-sc commented on src/target/riscv/riscv-013.c
> +	/* This would be nice to move this redirection, to version-independent part,
Addressed.

2024-01-23 15:01 UTC, MarekVCodasip commented on src/target/riscv/riscv-013.c
> +	/* This would be nice to move this redirection, to version-independent part,
Thanks.

2024-01-23 15:01 UTC, MarekVCodasip approved these changes

2024-01-24 08:01 UTC, JanMatCodasip commented
Let's merge this on Thursday if no other feedback comes.

2024-01-25 05:52 UTC, JanMatCodasip commented
> TommyMurphyTM1234: Confirmed as working with SiFive HiFive1 Rev A01: [...]

Thanks for checking it. :+1:

2024-01-25 05:53 UTC, merged

2024-01-25 09:30 UTC, lz-bro commented
Need to move write register for priv  to riscv-013.c?

2024-01-26 09:37 UTC, en-sc commented
> Need to move write register for priv to riscv-013.c?

@iz-bro, this is a valid concern. However, I've decided not to move the write in this commit.
The reasoning is:
* This is a bug-fix. Bug is related to reading the register, not writing it.
* Assuming the other code is correct, only a user-requested write can cause an issue with writing `dcsr[5]` via writing `priv` on 0.11.

I'm currently working on a patch that significantly changes register accesses. I will post a PR changing the code in question soon. So, I would like not to change current version too much to avoid doing extra work).